=== Chuanhsing/libggpk/LibDat/schemas/DatDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by MIchael (MIPT) -->
<!-- W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="bool"/>
				<xs:enumeration value="byte"/>
				<xs:enumeration value="short"/>
				<xs:enumeration value="int"/>
				<xs:enumeration value="Int64"/>
				<!--	insert more here -->
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pointer">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=""/>
				<xs:enumeration value="Int32Index"/>
				<xs:enumeration value="UInt32Index"/>
				<xs:enumeration value="UInt64Index"/>
				<xs:enumeration value="DataIndex"/>
				<xs:enumeration value="StringIndex"/>
				<xs:enumeration value="UserStringIndex"/>
				<xs:enumeration value="IndirectStringIndex"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string"/>
				<xs:element ref="type"/>
				<xs:element ref="pointer"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="definition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string"/>
			<xs:attribute name="record_length" type="xs:nonNegativeInteger" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="dat_id" type="xs:string"/>
	<xs:element name="definitions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="definition" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Chuanhsing/libggpk/LibDat/DatDefinitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by MIchael (MIPT) -->
<definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./DatDefinitions.xsd">
	<definition id="AchievementItems" record_length="28">
		<field>
			<description>Id</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Unknown1</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown2</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Name</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Unknown4</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown5</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown6</description>
			<type>int</type>
			<pointer/>
		</field>
	</definition>
	<definition id="Achievements" record_length="22">
		<field>
			<description>Id</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Description</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Unknown2</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Objective</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Unknown4</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Flag0</description>
			<type>bool</type>
			<pointer/>
		</field>
		<field>
			<description>Flag1</description>
			<type>bool</type>
			<pointer/>
		</field>
	</definition>
	<definition id="AchievementSets"/>
	<definition id="ActiveSkills" record_length="70">
		<field>
			<description>NameIndex</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>DisplayedName</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Description</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Index3</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>IconPath</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Data0_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data0</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Unknown1</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data1_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data1</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Data2_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data2</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>WebsiteDescription</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>WebsiteImage</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Flag0</description>
			<type>bool</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown4</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Flag1</description>
			<type>bool</type>
			<pointer/>
		</field>
		<field>
			<description>Metadata</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
	</definition>
	<definition id="ActiveSkillTargetTypes"/>
	<definition id="ActiveSkillType"/>
	<definition id="ArmourClasses"/>
	<definition id="ArmourSurfaceTypes"/>
	<definition id="ArmourTypes" record_length="8">
		<field>
			<description>ItemKey</description>
			<type>Int64</type>
			<pointer/>
		</field>
	</definition>
	<definition id="Attributes"/>
	<definition id="BackendErrors" record_length="8">
		<field>
			<description>Id</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Text</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
	</definition>
	<definition id="BaseItemTypes" record_length="176">
		<field>
			<description>Index0</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>ItemClass</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Width</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Height</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Name</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>InheritsFrom</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Unknown3</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown4</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Data0_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data0</description>
			<type>int</type>
			<pointer>UInt64Index</pointer>
		</field>
		<field>
			<description>Unknown6</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown7</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown8</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown9</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown10</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Data1_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data1</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Data2_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data2</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Data3_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data3</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Data4_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data4</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Data5_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data5</description>
			<type>int</type>
			<pointer>UInt64Index</pointer>
		</field>
		<field>
			<description>Unknown16</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown17</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown18</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data6_Length</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Data6</description>
			<type>int</type>
			<pointer>UInt32Index</pointer>
		</field>
		<field>
			<description>Unknown34</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown36</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown37</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown38</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown39</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown40</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown41</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown42</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown43</description>
			<type>int</type>
			<pointer/>
		</field>
	</definition>
	<definition id="BeyondDemons">
		<field>
			<description>Unknown0</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Unknown1</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Flag0</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Flag1</description>
			<type>int</type>
			<pointer/>
		</field>
	</definition>
	<definition id="BindableVirtualKeys" record_length="12">
		<field>
			<description>KeyCode</description>
			<type>int</type>
			<pointer/>
		</field>
		<field>
			<description>Name</description>
			<type>int</type>
			<pointer>UserStringIndex</pointer>
		</field>
		<field>
			<description>Id</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
	</definition>
	<definition id="BloodTypes" record_length="60">
		<field>
			<description>Id</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Index1</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Index2</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Index3</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Unknown4</description>
			<type>Int64</type>
			<pointer/>
		</field>
		<field>
			<description>Index4</description>
			<type>int</type>
			<pointer>StringIndex</pointer>
		</field>
		<field>
			<description>Index5</description>
